#!/usr/bin/env python3

import configparser
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk
import os
import os.path
import shutil
import signal
import subprocess

DESKTOP_FILE_ENDING = '.desktop'
DESKTOP_ENTRY_SECTION = 'Desktop Entry'
CONFIG_SECTION_APPEARANCE = 'appearance'
CONFIG_SECTION_APPLICATIONS = 'applications'
CONFIG_SECTION_DAEMONS = 'daemons'
CONFIG_SECTION_INPUT = 'input'
DIRNAME = 'pademelon'
PADEMELON_DAEMON_BINARY = 'pademelon-daemon'
PREFERENCE_NONE = 'none'
TEST_TIMEOUT = 1    # in seconds
TITLE = 'Pademelon Settings'

category_names = {
        # CONFIG_SECTION_DAEMONS
        'window-manager' : 'X11WindowManager',
        'compositor' : 'X11Compositor',
        'dock' : 'Dock',
        'hotkeys' : 'HotkeyDaemon',
        'notifications' : 'NotificationDaemon',
        'polkit' : 'Polkit',
        'power' : 'PowerManager',
        'status' : 'Status',
        'applets' : 'Applet',
        'optional' : 'Optional',
        # CONFIG_SECTION_APPLICATIONS
        'browser' : 'WebBrowser',
        'dmenu' : 'AppLauncher',
        'filemanager' : 'FileManager',
        'terminal' : 'TerminalEmulator',
}

child_processes = []

class ApplicationBox(Gtk.Box):
    def __init__(self, window, config_section, cname, clabel):
        super().__init__()
        global categories
        self.window = window
        self.config_section = config_section
        self.cname = cname
        self.clabel = clabel

        if cname in category_names.keys() and category_names[cname] in categories:
            self.applications = categories[category_names[cname]]
        else:
            self.applications = []

        self.frame = Gtk.Frame()
        self.frame.set_label(clabel)
        self.frame.set_margin_end(5)
        self.frame.set_margin_start(5)

        self.pack_start(self.frame, True, True, 0)


class ApplicationSelectionBox(ApplicationBox):
    def __init__(self, window, config_section, cname, clabel):
        super().__init__(window, config_section, cname, clabel)
        global config

        self.inner_box = Gtk.Box()
        self.settings_button = Gtk.Button(label='Settings')
        self.settings_button.connect('clicked', self.on_button_clicked)
        self.application_selection_box = Gtk.ComboBoxText()

        select = len(self.applications) + 1      # select default item
        for application in self.applications:
            self.application_selection_box.append_text(application.display_name + self.application_test_str(application))
            if self.config_section in config \
                    and self.cname in config[self.config_section] \
                    and application.id_name == config[self.config_section][cname]:
                        # @TODO generalize section name for applications
                select = self.applications.index(application)     # select config item if existent
                self.application_selection_box.set_tooltip_text(application.desc)
        if self.config_section in config \
                and self.cname in config[self.config_section] \
                and PREFERENCE_NONE == config[self.config_section][cname]:
            select = len(self.applications)
        self.application_selection_box.append_text('None')
        self.application_selection_box.append_text('Default')
        self.application_selection_box.set_active(select)
        self.application_selection_box.connect("changed", self.on_combo_changed)

        self.inner_box.pack_start(self.application_selection_box, True, True, 5)
        self.inner_box.pack_end(self.settings_button, False, False, 5)
        self.frame.add(self.inner_box)

    def application_test_str(self, application):
        if application.test():
            return ''
        else:
            return ' (not installed)'

    def on_button_clicked(self, source):
        if source is not self.settings_button:
            return
        selected = self.selected_application()
        if selected == None:
            return
        if selected.settings == '':
            Dialog.no_settings_available(selected.display_name, self.window)
            return
        if selected.settings.startswith("config://"):
            path = os.getenv('XDG_CONFIG_HOME', os.path.expanduser('~/.config'))
            if not os.path.exists(os.path.dirname(path)) and Dialog.create_parent_dir(self.window):   # give user chance to create parent dir
                os.makedirs(os.path.dirname(path))
            spawn(['xdg-open', os.path.join(path, selected.settings[len('config://'):])], check_dependency=True, parent=self.window)
        elif selected.settings.startswith('file://'):
            path = selected.settings[len('file://'):]
            if not os.path.exists(os.path.dirname(path)) and Dialog.create_parent_dir(self.window):   # give user chance to create parent dir
                os.makedirs(os.path.dirname(path))
            spawn(['xdg-open', path], check_dependency=True, parent=self.window)
        else:
            spawn(['/bin/sh', '-c', selected.settings], check_dependency=True, parent=self.window)

    def on_combo_changed(self, combo):
        selected = self.selected_application();
        if selected == None:
            if self.application_selection_box.get_active() == len(self.applications):   # none
                if self.config_section not in config:
                    config[self.config_section] = {}
                config[self.config_section][self.cname] = PREFERENCE_NONE
            else: # default
                if self.config_section in config and self.cname in config[self.config_section]:
                    config.remove_option(self.config_section, self.cname)
                self.application_selection_box.set_has_tooltip(False)
            self.settings_button.set_relief(Gtk.ReliefStyle.NONE)
        else:
            if not selected.test():
                Dialog.program_not_available(selected.id_name, self.window)
            if self.config_section not in config:
                config[self.config_section] = {}
            config[self.config_section][self.cname] = selected.id_name
            self.application_selection_box.set_tooltip_text(selected.desc)
            if selected.settings == '':
                self.settings_button.set_relief(Gtk.ReliefStyle.NONE)
            else:
                self.settings_button.set_relief(Gtk.ReliefStyle.NORMAL)

    def selected_application(self):
        selection = self.application_selection_box.get_active()
        if selection >= len(self.applications):  # default, none
            return None
        else:
            return self.applications[selection]


class DesktopApplication():
    def __init__(self, id_name):
        self.id_name = id_name
        self.display_name = id_name
        self.desc = ""
        self.category = "Optional"
        self.cdefault = False
        self.launch_cmd = ""
        self.test_cmd = ""
        self.settings = ""
        self.tested = False
        self.test_result = False

    def run_test(self):
        try:
            cp = subprocess.run(self.test_cmd, shell=True, timeout=TEST_TIMEOUT)
            self.tested = True
            self.test_result = cp.returncode == 0
        except subprocess.TimeoutExpired:
            self.tested = True
            self.test_result = 0
        return self.test_result

    def test(self):
        if not self.tested:
            self.run_test()
        return self.test_result


class Dialog():
    @staticmethod
    def create_parent_dir(parent=None):
        dialog = Gtk.MessageDialog(
                transient_for = parent,
                message_type = Gtk.MessageType.QUESTION,
                buttons = Gtk.ButtonsType.YES_NO,
                text = 'Parent directory for config file does not exist. Create it now?')
        dialog.set_title('Config Directory')
        dialog.show()
        response = dialog.run()
        if response == Gtk.ResponseType.YES:
            dialog.destroy()
            return True
        else:
            dialog.destroy()
            return False

    @staticmethod
    def logout_login(parent=None):
            dialog = Gtk.MessageDialog(
                    transient_for = parent,
                    message_type = Gtk.MessageType.ERROR,
                    buttons = Gtk.ButtonsType.OK,
                    text = 'Warning: Some changes might require you to log out and log back in again to take effect.')
            dialog.set_title('Some changes might not be updated')
            dialog.show()
            dialog.run()
            dialog.destroy()

    @staticmethod
    def missing_dependency(name, parent=None):
        msg = "You are missing the binary dependency: {}\nPlease use your package manager to install it manually."
        msg = msg.format(name)
        dialog = Gtk.MessageDialog(
                transient_for = parent,
                message_type = Gtk.MessageType.ERROR,
                buttons = Gtk.ButtonsType.OK,
                text = msg)
        dialog.set_title("Missing Binary Dependency")
        dialog.show()
        dialog.run()
        dialog.destroy()

    @staticmethod
    def no_parent_dir(path, parent=None):
        dialog = Gtk.MessageDialog(
                transient_for = parent,
                message_type = Gtk.MessageType.ERROR,
                buttons = Gtk.ButtonsType.OK,
                text = 'Unable to write config to "{}". Parent directory does not exist.'.format(path))
        dialog.set_title('Unable to Write Config')
        dialog.show()
        dialog.run()
        dialog.destroy()

    @staticmethod
    def no_settings_available(name, parent=None):
            dialog = Gtk.MessageDialog(
                    transient_for = parent,
                    message_type = Gtk.MessageType.ERROR,
                    buttons = Gtk.ButtonsType.OK,
                    text = 'No settings file or application found for "{}".'.format(name))
            dialog.set_title('No Settings Available')
            dialog.show()
            dialog.run()
            dialog.destroy()

    @staticmethod
    def program_not_available(name, parent=None):
        dialog = Gtk.MessageDialog(
                transient_for = parent,
                message_type = Gtk.MessageType.WARNING,
                buttons = Gtk.ButtonsType.OK,
                text = 'You selected a program, that is not installed or not available: "{}". '.format(name)
                + 'You might want want to either install that program or choose another one.')
        dialog.set_title('Program not installed')
        dialog.show()
        dialog.run()
        dialog.destroy()


class MainWindow(Gtk.Window):
    def __init__(self):
        super().__init__(title=TITLE)
        self.notebook_pages = []
        self.set_border_width(10)
        self.set_default_size(600, 800)

        # create ui elements
        self.main_box = Gtk.Box()
        self.main_box.set_orientation(Gtk.Orientation.VERTICAL)
        self.scrolled_window = Gtk.ScrolledWindow()
        self.notebook = Gtk.Notebook()
        self.action_bar = Gtk.ActionBar()
        self.save_reload_button = Gtk.Button(label="Save and Reload")
        self.save_reload_button.connect('clicked', self.on_button_clicked)
        self.cancel_button = Gtk.Button(label="Cancel")
        self.cancel_button.connect('clicked', self.on_button_clicked)
        self.save_button = Gtk.Button(label="Save")
        self.save_button.connect('clicked', self.on_button_clicked)
        self.quit_button = Gtk.Button(label="Save & Exit")
        self.quit_button.connect('clicked', self.on_button_clicked)

        # add pages for notebook
        self.notebook_pages.append(('Daemons', self.daemon_page()))
        self.notebook_pages.append(('Applications', self.application_page()))
        self.notebook_pages.append(('System', self.system_page()))
        for page in self.notebook_pages:
            self.notebook.append_page(page[1], Gtk.Label(label=page[0]))

        # compose ui
        self.main_box.pack_start(self.notebook, True, True, 0)
        self.main_box.pack_end(self.action_bar, False, False, 0)
        if (getpid(PADEMELON_DAEMON_BINARY) > 0):
            self.action_bar.pack_start(self.save_reload_button)
        self.action_bar.pack_end(self.quit_button)
        self.action_bar.pack_end(self.save_button)
        self.action_bar.pack_end(self.cancel_button)

        self.scrolled_window.add(self.main_box)
        self.add(self.scrolled_window)
        self.show_all()
        self.set_position(Gtk.WindowPosition.CENTER)
        self.connect('destroy', Gtk.main_quit)

    def application_page(self):
        self.application_rows = []

        # init applications box
        self.applications_box = Gtk.Box(orientation=Gtk.Orientation.VERTICAL)
        self.applications_box.set_spacing(5)

        # create application frames
        self.application_rows.append(ApplicationSelectionBox(self, CONFIG_SECTION_APPLICATIONS, 'terminal', 'Terminal Emulator'))
        self.application_rows.append(ApplicationSelectionBox(self, CONFIG_SECTION_APPLICATIONS, 'filemanager', 'File Manager'))
        self.application_rows.append(ApplicationSelectionBox(self, CONFIG_SECTION_APPLICATIONS, 'browser', 'Web Browser'))
        self.application_rows.append(ApplicationSelectionBox(self, CONFIG_SECTION_APPLICATIONS, 'dmenu', 'Application Menu'))

        # add application frames to box
        for ar in self.application_rows:
            self.applications_box.pack_start(ar, False, False, 5)

        return self.applications_box


    def daemon_page(self):
        self.daemon_rows = []

        # init daemons box
        self.daemons_box = Gtk.Box(orientation=Gtk.Orientation.VERTICAL)
        self.daemons_box.set_spacing(5)
        self.applet_box = OptionalApplicationBox(self, CONFIG_SECTION_DAEMONS, 'applets', 'Applets')
        self.optional_box = OptionalApplicationBox(self, CONFIG_SECTION_DAEMONS, 'optional', 'Other optional daemons')

        # create daemon frames
        self.daemon_rows.append(ApplicationSelectionBox(self, CONFIG_SECTION_DAEMONS, 'window-manager', 'Window Manager'))
        self.daemon_rows.append(ApplicationSelectionBox(self, CONFIG_SECTION_DAEMONS, 'compositor', 'Compositor'))
        self.daemon_rows.append(ApplicationSelectionBox(self, CONFIG_SECTION_DAEMONS, 'dock', 'Dock'))
        self.daemon_rows.append(ApplicationSelectionBox(self, CONFIG_SECTION_DAEMONS, 'hotkeys', 'Hotkey Daemon'))
        self.daemon_rows.append(ApplicationSelectionBox(self, CONFIG_SECTION_DAEMONS, 'notifications', 'Notification Daemon'))
        self.daemon_rows.append(ApplicationSelectionBox(self, CONFIG_SECTION_DAEMONS, 'polkit', 'Polkit'))
        self.daemon_rows.append(ApplicationSelectionBox(self, CONFIG_SECTION_DAEMONS, 'power', 'Power Management'))
        self.daemon_rows.append(ApplicationSelectionBox(self, CONFIG_SECTION_DAEMONS, 'status', 'Status Script or Bar'))

        # add daemon frames to box
        for dr in self.daemon_rows:
            self.daemons_box.pack_start(dr, False, False, 5)

        self.daemons_box.pack_start(self.applet_box, False, False, 5)
        self.daemons_box.pack_start(self.optional_box, False, False, 5)

        return self.daemons_box

    def system_page(self):
        # init main box
        self.system_box = Gtk.Box(orientation=Gtk.Orientation.VERTICAL)
        self.system_box.set_spacing(5)

        # display frame
        self.display_frame = Gtk.Frame()
        self.display_frame.set_label('Display')
        self.display_frame.set_margin_end(5)
        self.display_frame.set_margin_start(5)
        self.display_box = Gtk.Box()
        self.arandr_button = Gtk.Button(label='Configure Display Layout')
        self.arandr_button.connect('clicked', self.on_button_clicked)
        self.display_box.pack_start(self.arandr_button, True, True, 5)
        self.display_frame.add(self.display_box)

        # appearance frame
        self.appearance_frame = Gtk.Frame()
        self.appearance_frame.set_label('Appearance')
        self.appearance_frame.set_margin_end(5)
        self.appearance_frame.set_margin_start(5)
        self.appearance_box = Gtk.Box()
        self.appearance_box.set_orientation(Gtk.Orientation.VERTICAL)
        self.wallpaper_button = Gtk.Button(label='Choose Wallpaper')
        self.wallpaper_button.connect('clicked', self.on_button_clicked)
        self.lookandfeel_button = Gtk.Button(label='Customize Look and Feel')
        self.lookandfeel_button.connect('clicked', self.on_button_clicked)
        self.appearance_box.pack_start(self.wallpaper_button, True, True, 2)
        self.appearance_box.pack_start(self.lookandfeel_button, True, True, 2)
        self.appearance_frame.add(self.appearance_box);

        # input frame
        self.input_frame = Gtk.Frame()
        self.input_frame.set_label('Input')
        self.input_frame.set_margin_end(5)
        self.input_frame.set_margin_start(5)
        self.input_box = Gtk.Box()
        self.keyboard_label = Gtk.Label()
        self.keyboard_label.set_text('Keyboard Layout:')
        self.keyboard_entry = Gtk.Entry()
        self.keyboard_entry.connect("changed", self.on_entry_changed)
        if CONFIG_SECTION_INPUT in config and 'keyboard-layout' in config[CONFIG_SECTION_INPUT]:
            self.keyboard_entry.set_text(config[CONFIG_SECTION_INPUT]['keyboard-layout'])
        self.input_box.pack_start(self.keyboard_label, False, False, 5)
        self.input_box.pack_start(self.keyboard_entry, True, True, 5)
        self.input_frame.add(self.input_box)

        # add menu items
        self.system_box.add(self.display_frame)
        self.system_box.add(self.appearance_frame)
        self.system_box.add(self.input_frame)

        return self.system_box

    def on_button_clicked(self, source):
        global config
        if source == self.arandr_button:
            spawn(["arandr"], check_dependency=True, parent=self)
        elif source == self.wallpaper_button:
            dialog = Gtk.FileChooserDialog(title="Choose background image",
                    parent=self,
                    action=Gtk.FileChooserAction.OPEN)
            dialog.add_buttons(
                    Gtk.STOCK_CANCEL,
                    Gtk.ResponseType.CANCEL,
                    Gtk.STOCK_OPEN,
                    Gtk.ResponseType.OK)
            response = dialog.run()
            if response == Gtk.ResponseType.OK:
                print("Setting new wallpaper: " + dialog.get_filename())
                spawn(["pademelon-tools", "set-wallpaper", dialog.get_filename()], check_dependency=True, parent=self)
            dialog.destroy()
        elif source == self.lookandfeel_button:
            spawn(["lxappearance"], check_dependency=True, parent=self)
        # action bar
        elif source == self.save_reload_button:
            write_config(config, user_config_path('pademelon.conf'), self)
            # Dialog.logout_login(self);
            pid = getpid(PADEMELON_DAEMON_BINARY)
            if (pid > 0):
                os.kill(pid, signal.SIGUSR1)
        elif source == self.cancel_button:
            Gtk.main_quit()
        elif source == self.save_button:
            write_config(config, user_config_path('pademelon.conf'), self)
        elif source == self.quit_button:
            write_config(config, user_config_path('pademelon.conf'), self)
            Gtk.main_quit()

    def on_entry_changed(self, entry):
        global config
        if entry == self.keyboard_entry:
            if CONFIG_SECTION_INPUT not in config:
                config[CONFIG_SECTION_INPUT] = {}
            config[CONFIG_SECTION_INPUT]['keyboard-layout'] = self.keyboard_entry.get_text()


class OptionalApplicationBox(ApplicationBox):
    def __init__(self, window, config_section, cname, clabel):
        super().__init__(window, config_section, cname, clabel)
        global config

        self.inner_box = Gtk.FlowBox()
        self.inner_box.set_selection_mode(Gtk.SelectionMode.NONE)
        self.check_buttons = []

        if self.config_section in config and cname in config[self.config_section]:
            self.activated_applications = set(config[self.config_section][cname].split(' '))
        else:
            self.activated_applications = set()

        for application in self.applications:
            cb = Gtk.CheckButton(label=application.display_name)
            cb.connect("toggled", self.on_button_toggled, "1")
            cb.set_tooltip_text(application.desc)
            if application.id_name in self.activated_applications:
                cb.set_active(True)
            self.check_buttons.append(cb)
            if application.test():
                self.inner_box.add(cb)

        if (len(self.inner_box.get_children()) == 0):
            self.remove(self.frame)
        else:
            self.frame.add(self.inner_box)

    def on_button_toggled(self, button, name):
        global config
        for cb in self.check_buttons:
            application_id_name = self.applications[self.check_buttons.index(cb)].id_name
            if cb.get_active() and application_id_name not in self.activated_applications:
                self.activated_applications.add(application_id_name)
            elif not cb.get_active() and application_id_name in self.activated_applications:
                self.activated_applications.remove(application_id_name)
        if self.config_section not in config:
            config[self.config_section] = {}
        config[self.config_section][self.cname] = ' '.join(self.activated_applications)


def check_binary_dependency(executable, parent=None):
    if type(executable) == str:
        temp = shutil.which(executable)
    else:
        temp = shutil.which(executable[0])
    if temp == None:
        Dialog.missing_dependency(executable, parent)
        return False
    else:
        return True

def getpid(pname):
    for dirname in os.listdir('/proc'):
        if dirname == 'curproc':
            continue

        try:
            with open('/proc/{}/cmdline'.format(dirname), mode='rb') as fd:
                content = fd.read().decode().split('\x00')
        except Exception:
            continue

        if pname in content[0]:
            return int(dirname)
    return -1

def parse_categories(value):
    for cat in value.split(','):
        if cat in category_names.values():
            return cat
        elif cat == 'TrayIcon':
            return 'Applet'
        elif cat == 'Panel':
            return 'Status'
    return None

def read_config(paths):
    config = configparser.ConfigParser()
    config.read(paths)
    return config

def read_desktop_application_files(paths):
    categories = {}
    files = []

    for path in paths:
        files.extend([f.path for f in os.scandir(path) if f.is_file() and f.path.endswith(DESKTOP_FILE_ENDING)])


    # read config files
    config = configparser.ConfigParser()
    # if len(config.read(files)) == 0:
    #     return None

    for filename in files:
        if len(config.read(filename)) == 0:
            continue

        application = DesktopApplication(os.path.basename(filename)[:-len(DESKTOP_FILE_ENDING)])
        try:
            application.display_name = config[DESKTOP_ENTRY_SECTION]['Name']
        except KeyError:
            print("Error while reading application config '{}': 'Name' not specified".format(application_id_name))

        # optional values
        if ('Comment' in config[DESKTOP_ENTRY_SECTION]):
            application.desc = config[DESKTOP_ENTRY_SECTION]['Comment']
        if ('Categories' in config[DESKTOP_ENTRY_SECTION]):
            application.category = parse_categories(config[DESKTOP_ENTRY_SECTION]['Categories'])
            if application.category == None:
                application.category = 'Optional'
        if ('Exec' in config[DESKTOP_ENTRY_SECTION]):
            application.launch_cmd = config[DESKTOP_ENTRY_SECTION]['Exec']
        if ('TryExec' in config[DESKTOP_ENTRY_SECTION]):
            application.test_cmd = "test -x " + config[DESKTOP_ENTRY_SECTION]['TryExec']
        if ('X-Pademelon-Settings' in config[DESKTOP_ENTRY_SECTION]):
            application.settings = config[DESKTOP_ENTRY_SECTION]['X-Pademelon-Settings']

        # add application to the right category
        if (application.category not in categories):
            categories[application.category] = []
        categories[application.category].append(application)

    return categories


def spawn(executable, check_dependency=False, parent=None):
    global child_processes
    if check_dependency and not check_binary_dependency(executable, parent):
        return
    temp = shutil.which(executable[0])
    if temp != None:
        child_processes.append(subprocess.Popen(executable))


def str_to_bool(s):
    return s.lower() in ['true', '1']


def system_config_path(file=''):
    return os.path.join('/etc', DIRNAME, file)


def system_data_path(file=''):
    return os.path.join('/usr/share', DIRNAME, file)


def system_local_data_path(file=''):
    return os.path.join('/usr/local/share', DIRNAME, file)


def user_config_path(file=''):
    path = os.getenv('XDG_CONFIG_HOME', os.path.expanduser('~/.config'))
    return os.path.join(path, DIRNAME, file)


def user_data_path(file=''):
    path = os.getenv('XDG_DATA_HOME', os.path.expanduser('~/.local/share'))
    return os.path.join(path, DIRNAME, file)


def write_config(config, path, parent=None):
    if not os.path.exists(os.path.dirname(path)) and Dialog.create_parent_dir(parent):   # give user chance to create parent dir
        os.makedirs(os.path.dirname(path))
    if not os.path.exists(os.path.dirname(path)):
        Dialog.no_parent_dir(path, parent)
        return
    if os.path.exists(path):
        pass # file already exists - overwrite?
    file = open(path, 'w+')
    config.write(file)
    file.close()


if __name__ == '__main__':
    categories = read_desktop_application_files([system_data_path('applications'),
            system_local_data_path('applications'), user_data_path('applications')])
    config = read_config([system_config_path('pademelon.conf'), user_config_path('pademelon.conf')])
    MainWindow()
    Gtk.main()
    for process in child_processes:
        process.terminate()
